name: Build and test (Mac OS)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'examples/**'
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '.github/workflows/macos.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'examples/**'
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '.github/workflows/macos.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: 1.86.0
    - uses: actions/checkout@v4
    - name: Build
      run: |
       git submodule update --init
       cargo build --verbose
    - name: Run tests
      run: |
       cargo test --features ci-headless --verbose
       # Release can have different build configuration, so test it
       cargo test --release --features=ci-headless --verbose
       # Test packaging (building from .crate archive, without SFML submodule)
       cargo package
    - name: TMate debug tests
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
